language: node_js
node_js:
    - "6.9.2"
cache: 
  - apt
  - pip
install:
    - "sudo apt-get update"
    - "sudo apt-get install python"
    - "python --version"
    - "sudo apt-get -y install python-dev"
    - "sudo apt-get -y install python-pip"
    - "pip install --user awscli"
    - "pip --help"
    - "mkdir dist"
    - "aws --version"
script: 
    - npm install
    - npm run prod
    - aws --region sa-east-1 s3 sync . s3://eventosdobem-frontend --acl public-read --exclude "package.json" --exclude ".travis.yml" --exclude "bitbucket-pipelines.yml" --exclude "docker-local.sh" --exclude ".git/*" --exclude ".config/*" --exclude ".npm/*" --exclude "node_modules/*"
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id E2GGIDEF1PPNTQ --paths "/*"
notifications:
    email:
        on_failure: always