# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.2

pipelines:
  branches:
    master:
      - step:
          script: 
           - apt-get update
           - python --version
           - sudo apt-get install python2.7
           - python --version
           - apt-get -y install python-pip
           - pip install awscli
           - pip --help
           - aws --version
           - aws --region us-east-1 s3 sync . s3://eventosdobem-frontend --acl public-read
           - aws configure set preview.cloudfront true
           - aws cloudfront create-invalidation --distribution-id E2GGIDEF1PPNTQ --paths /*
    production:
      - step:
          script:
           - apt-get update
           - apt-get -y install python-pip
           - pip install awscli
           - aws --version
           - echo "This script runs only on commit to the production branch."
           - aws --region sa-east-1 s3 sync . s3://eventosdobem.com.br --acl public-read
           - aws configure set preview.cloudfront true
           - aws cloudfront create-invalidation --distribution-id E1CX7CDU68AMAR --paths /*