# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.2

pipelines:
  custom:
    deploy-to-staging:
      - step:
          script: 
           - apt-get update
           - python --version
           - apt-get -y install python-dev
           - apt-get -y install python-pip
           - pip install awscli
           - pip --help
           - npm install
           - npm run prod
           - aws --version
           - aws --region sa-east-1 s3 sync . s3://eventosdobem-frontend --acl public-read --exclude ".git/*" --exclude ".config/*" --exclude ".npm/*" --exclude "node_modules/*"
           - aws configure set preview.cloudfront true
           - aws cloudfront create-invalidation --distribution-id E2GGIDEF1PPNTQ --paths "/*"
    deploy-to-production:
      - step:
          script: 
           - apt-get update
           - python --version
           - apt-get -y install python-dev
           - apt-get -y install python-pip
           - pip install awscli
           - pip --help
           - npm install
           - npm run prod
           - aws --version
           - aws --region sa-east-1 s3 sync . s3://eventosdobem-frontend --acl public-read --exclude ".git/*" --exclude ".config/*" --exclude ".npm/*" --exclude "node_modules/*"
           - aws configure set preview.cloudfront true
           - aws cloudfront create-invalidation --distribution-id E1CX7CDU68AMAR --paths "/*"
  branches:
    master:
      - step:
          script: 
           - apt-get update
           - python --version
           - apt-get -y install python-dev
           - apt-get -y install python-pip
           - pip install awscli
           - pip --help
           - npm install
           - npm run prod
           - aws --version
           - aws --region sa-east-1 s3 sync . s3://eventosdobem-frontend --acl public-read --exclude ".git/*" --exclude ".config/*" --exclude ".npm/*" --exclude "node_modules/*"
           - aws configure set preview.cloudfront true
           - aws cloudfront create-invalidation --distribution-id E2GGIDEF1PPNTQ --paths "/*"
    production:
      - step:
          script: 
           - apt-get update
           - python --version
           - apt-get -y install python-dev
           - apt-get -y install python-pip
           - pip install awscli
           - pip --help
           - npm install
           - npm run prod
           - aws --version
           - aws --region sa-east-1 s3 sync . s3://eventosdobem-frontend-production --acl public-read --exclude ".git/*" --exclude ".config/*" --exclude ".npm/*" --exclude "node_modules/*"
           - aws configure set preview.cloudfront true
           - aws cloudfront create-invalidation --distribution-id E1CX7CDU68AMAR --paths "/*"